# Generated by Django 2.2 on 2019-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
