# Generated by Django 2.2 on 2019-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_organisation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(default='NO_PHONE', max_length=100),
        ),
    ]
