# Generated by Django 2.2 on 2019-07-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_organisation_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='name',
        ),
    ]
