# Generated by Django 2.2 on 2019-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0005_auto_20190711_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='alloted_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='donator',
            field=models.IntegerField(null=True),
        ),
    ]
