# Generated by Django 2.2 on 2019-07-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0006_auto_20190711_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='units',
            field=models.CharField(default='No.s', max_length=255),
        ),
    ]
